---
# Create ROSA NameSpace
# Parameter namespace_name, api_url, api_token
- hosts: localhost
  tasks:
    - name: Create a NameSpace
      kubernetes.core.k8s:
        name: "{{ namespace_name }}"
        api_version: v1
        host: "{{ api_url }}"
        api_key: "{{ api_token }}"
        kind: Namespace
        state: present
