---
# Playbook ev01_create_namespace
# Create ROSA NameSpace
# Parameter: 
# - namespace_name
- hosts: localhost
  tasks:
    - name: Create a NameSpace
      kubernetes.core.k8s:
        name: "{{ namespace_name }}"
        api_version: v1
        kind: Namespace
        state: present
