---
# Delete ROSA NameSpace
# Parameter namespace_name
- hosts: localhost
  tasks:
    - name: Delete a NameSpace
      kubernetes.core.k8s:
        name: "{{ namespace_name }}"
        api_version: v1
        kind: Namespace
        state: absent
