---
# Playbook ev03_create_secret
# Create a Secret
# Parameter 
- hosts: localhost
  tasks:
    - name: Create a Image Pull Secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            namespace: "{{ namespace_name }}"
            name: "{{ image_pull_secret_name }}"
          data:
            .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjbWh1WDJOdmJuTjFiSFJwYm1kZmEyVnRiM0pwT2xWdGNHTTFiMkZaZVZFdk1EaG9WamhtVW5WV05HazJUemR5VG5sVFp6Qk9aRmhpVFVSb2MyTjVUM2MzZGpoNU1UbFVUM2hsUm1SalpYbHVZMXAzYWs0PSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9Cg==
            type: kubernetes.io/dockerconfigjson
