---
# Playbook ev09_delete_job
# Delete All Jobs
# Parameter: 
# - namespace_name
- hosts: localhost
  tasks:
    - name: Delete All Jobs
      kubernetes.core.k8s:
        api_version: batch/v1
        kind: Job
        namespace: "{{ namespace_name }}"
        delete_all: true
