# L1_02_environment_wf
# Parameter: 
# * test_id, test_result_seq, seq, name
# - result_manager_url, pipeline_repo_domain, pipeline_repo_name
# + pipeline_vars
- name: Gitclone & Set Paramete
  # namespace_name, create_table_image, insert_table_image
  ansible.builtin.import_playbook: L2_ev01_gitclone_setparam.yaml

- name: Create NameSpace
  ansible.builtin.import_playbook: L2_ev02_create_namespace.yaml

- name: Create Secret
  ansible.builtin.import_playbook: L2_ev03_create_secret.yaml

- name: Create Database
  ansible.builtin.import_playbook: L2_ev04_create_database.yaml

- name: Create Table
  ansible.builtin.import_playbook: L2_ev05_create_table.yaml

- name: Insert Table
  ansible.builtin.import_playbook: L2_ev06_insert_table.yaml

- name: End Provisioning
  ansible.builtin.import_playbook: L2_ev07_end_provisioning.yaml
  # L3_rp03_run_pipeline_summary.yaml
  # L3_rp05_run_complete_notification.yaml
  # L3_ut02_kick_nextpipeline.yaml
