---
# L2_st03_data_entry
# Parameter: 
# * test_id, test_result_seq, name, simulation_date
# - pipeline_repo_domain, pipeline_repo_name
# + pipeline_vars
- name: Start Scenario
  hosts: localhost
  tasks:
    # Git clone
    - name: Git clone
      ansible.builtin.import_tasks:
        file: L3_ut01_gitclone.yaml

    # Find j2 file
    - name: Find j2 files
      ansible.builtin.find:
        paths: /tmp/{{ pipeline_repo_name }}/{{ test_id }}/test_scenario/{{ name }}/p2_data_entry
        patterns: "*.j2"
        file_type: file
      register: found_files

    # Data Entry
    - name: Data Entry API
      ansible.builtin.include_tasks:
        file: L3_st05_call_api.yaml
      vars:
        source_j2_path: "{{ item.path }}"
        namespace_name: "{{ pipeline_vars.namespace_name }}"
        test_result_seq: "{{ test_result_seq }}"
        test_id: "{{ test_id }}"
        test_group: "テストシナリオ"
        test_pipeline: "バッチ処理"
        simulation_date: "{{ simulation_date }}"
        sw_category: "バッチ"
      loop: "{{ found_files.files }}"
      loop_control:
        label: "{{ item.path }}"

    # Report Summary
    - name: Report Pipeline Summary
      ansible.builtin.import_tasks:
        file: L3_rp03_run_pipeline_summary.yaml
      vars:
        test_group: "テストシナリオ"
        test_pipeline: "バッチ処理"
        simulation_date : "{{ simulation_date }}"
