# L3_st01_apply_openshift
# Parameter:
# * source_yaml_path
# + l3_st01_result
# + -> start_timestamp, end_timestamp, test_result
- name: Start timestamp
  ansible.builtin.debug:
    var: start_timestamp
  vars:
    start_timestamp: '{{ lookup(''pipe'', ''date "+%Y-%m-%d %H:%M:%S"'') }}'
  register: l3_st01_result

- name: Print Result Start
  ansible.builtin.debug:
    var: l3_st01_result

- name: Apply block
  block:
    - name: Apply Yaml
      kubernetes.core.k8s:
        state: present
        src: "{{ source_yaml_path }}"
      register: l3_st01_result

    - name: Print Result Apply Yaml
      ansible.builtin.debug:
        var: l3_st01_result

    - name: Set test_result
      ansible.builtin.debug:
        var: test_result
      vars:
        test_result: "OK"
      register: l3_st01_result
  
  rescue:
    - name: Set test_result
      ansible.builtin.debug:
        var: test_result
      vars:
        test_result: "NG"
      register: l3_st01_result

- name: End timestamp
  ansible.builtin.debug:
    var: end_timestamp
  vars:
    end_timestamp: '{{ lookup(''pipe'', ''date "+%Y-%m-%d %H:%M:%S"'') }}'
  register: l3_st01_result

- name: Print Result
  ansible.builtin.debug:
    var: l3_st01_result
