---
# L3_ut01_gitclone
- name: Git Clone
  ansible.builtin.git:
    repo: 'https://github.com/{{ pipeline_repo_domain }}/{{ pipeline_repo_name }}.git'
    dest: /tmp/{{ pipeline_repo_name }}

- name: include_vars
  include_vars: 
    file: /tmp/{{ pipeline_repo_name }}/{{ test_id }}/pipeline.yaml
    name: pipeline_vars

- name: print vars
  debug:
    msg: "{{ pipeline_vars }}"
