- name: Test Playbook
  hosts: localhost
  tasks:
    - name: Show Parameter
      ansible.builtin.debug:
        msg: "namespace_name={{ namespace_name }}, create_table_image={{ create_table_image }}, insert_table_image={{ insert_table_image }}"

    - name: Show Parameter2
      ansible.builtin.debug:
        var: database_request

    - name: Show Parameter2
      ansible.builtin.debug:
        var: kafka_request

    - name: Show Parameter2
      ansible.builtin.debug:
        var: create_table_request

    - name: Show Parameter2
      ansible.builtin.debug:
        var: insert_table_request
