---
# Playbook rp01_add_test_result
# Parameter: 
# - result_manager_url
# - test_id, test_name, test_description
- name: add _test_result 
  hosts: localhost
  tasks:
    - name: Add test_result
      ansible.builtin.uri:
        url: https://{{ result_manager_url }}/api/test_result
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
        body: |-
          {
            "test_id": "{{ test_id }}",
            "test_name": "{{ test_name }}",
            "test_description": "{{ test_description }}"
          }
      register: result

    - name: debug
      ansible.builtin.debug:
        var: result.test_result_seq
