- name: Test Playbook
  hosts: localhost
  tasks:
    - name: Git clone
      ansible.builtin.import_tasks:
        file: L3_ut01_gitclone.yaml
    
    - name: Search for string
      lineinfile:
        path: "/tmp/demo-itst-test/EX-E001-00000003/test_scenario/D2025-03-12/p1_run_online_app/report-viewer.j2"
        line: "app: "
        state: present
      check_mode: true
      register: result
      changed_when: false
      failed_when: "'line replaced' in result.msg"
      
    - name: Show result
      debug:
        var: result
