- name: Test Playbook
  hosts: localhost
  tasks:
    - name: debug
      ansible.builtin.debug:
        msg:
          api_url: "{{ api_url }}"
          api_token: "{{ api_token }}"

    - name: Get cluster version
      kubernetes.core.k8s_info:
        api_version: v1
        kind: ClusterVersion
        name: version
        host: "{{ api_url }}"
        api_key: "{{ api_token }}"
      register: cluster_version_info

    - name: print
      ansible.builtin.debug:
        var: cluster_version_info.resources[0].status.history[0].version
