- name: Test Playbook
  hosts: localhost
  tasks:
    - name: Git clone
      ansible.builtin.import_tasks:
        file: L3_ut01_gitclone.yaml
    
    - name: Check httpd.con
      shell: grep -E "app:" /tmp/demo-itst-test/EX-E001-00000003/test_scenario/D2025-03-12/p1_run_online_app/report-viewer.j2
      register: grep_result
      failed_when: grep_result.rc not in [0]
      
    - name: Show result
      debug:
        msg: "app-name={{ serch_line[1] }}"
      vars:
        serch_line: "{{ grep_result.stdout_lines[0] | split(':') | trim }}"
