- name: Test Playbook
  hosts: localhost
  tasks:
    - name: Git Clone
      ansible.builtin.git:
        repo: 'https://github.com/rhn-consulting-kemori/demo-itst-test.git'
        dest: /tmp/checkout

    - name: cat file
      shell: cat /tmp/checkout/README.md
      register: cat_file

    - name: echo file body
      debug:
        msg: "{{ cat_file.stdout }}"
