- name: Test Playbook
  hosts: localhost
  tasks:
    - name: Add test_task NG
      ansible.builtin.import_tasks:
        file: L3_rp02_add_test_task.yaml
      vars:
        test_group: "クロージング"
        test_pipeline: "環境スクラップ"
        test_task: "NameSpace削除"
        simulation_date: ""
        start_time: "2025/04/07 09:39:09"
        end_time: "2025/04/07 09:39:10"
        test_result: "OK"
        evidence_link: "-"
        sw_category: ""
        sw_id: ""
        sw_name: ""
        sw_version: ""
