- name: Test Playbook
  hosts: localhost
  tasks:
    - name: Git Clone
      ansible.builtin.git:
        repo: 'https://github.com/rhn-consulting-kemori/demo-itst-test.git'
        dest: /tmp/demo-itst-test

    - name: include_vars {{ item }} to tmp_vars
      include_vars: 
        file: /tmp/demo-itst-test/report-pipeline/pipeline.yaml
        name: tmp_vars

    - name: print vars
      debug:
        msg: "{{ tmp_vars }}"
