---
# Playbook ts01_run_online_app
# Run Online App
# Parameter: 
# * online_yaml
- hosts: localhost
  tasks:
    - name: Download Yaml
      ansible.builtin.get_url:
        url: https://github.com/rhn-consulting-kemori/demo-itst-test/blob/main/report-pipeline/test_scenario/online_run/report-viewer.yaml
        dest: ~/report-viewer.yaml
        mode: '0664'

    - name: Online App Deployment
      kubernetes.core.k8s:
        state: present
        src: ~/report-viewer.yaml

    - name: Delete tmp file
      ansible.builtin.file:
        path: ~/report-viewer.yaml
        state: absent
