---
# demo-itst-inventory
all:
  vars:
    openshift_domain: apps.rosa.rosa-vpfgs.o0sn.p3.openshiftapps.com # Change your Rosa Environment
    result_manager_url: result-manager-demo-report.apps.rosa.rosa-vpfgs.o0sn.p3.openshiftapps.com # Change your Rosa Environment
    report_viewer_url: report-viewer-demo-report.apps.rosa.rosa-vpfgs.o0sn.p3.openshiftapps.com # Change your Rosa Environment
    image_pull_secret_name: quayio
    database_app_name: postgresql
    pg_user: test
    pg_database: test
    pg_password: test
    pg_port: '5432'
    kafka_cluster_name: demo-cluster
    pipeline_repo_domain: rhn-consulting-kemori
    pipeline_repo_name: demo-itst-test
    aap_controller_url: https://controller.nht4t.sandbox2861.opentlc.com # Change your Ansible Environment
    aap_api_url: api/v2               # AAP2.5->api/controller/v2, Before->api/v2
    environment_pipeline_number: 62   # WorkFlow Number: L1_wf02_environment
    test_scenario_pipeline_number: 63 # WorkFlow Number: L1_wf03_test_scenario
    closing_pipeline_number: 64       # WorkFlow Number: L1_wf04_closing
    ansible_token: manual setup       # ToDo
    google_chat_url: manual setup     # ToDo
    pvc_name: demo-efs-pvc1
    pvc_access_mode: ReadWriteMany
    strage_class_name: efs-csi
    pvc_strage_size: 1Gi