---
all:
  vars:
    openshift-domain: apps.rosa.rosa-vpfgs.o0sn.p3.openshiftapps.com
    result_manager_url: result-manager-demo-report.apps.rosa.rosa-vpfgs.o0sn.p3.openshiftapps.com
    report_viewer_url: report-viewer-demo-report.apps.rosa.rosa-vpfgs.o0sn.p3.openshiftapps.com
    image_pull_secret_name: quayio
    database_app_name: postgresql
    pg_user: test
    pg_database: test
    pg_password: test
    pg_port: "5432"
    pipeline_repo_domain: rhn-consulting-kemori
    pipeline_repo_name: demo-itst-test
    aap_controller_url: https://controller.nht4t.sandbox2861.opentlc.com
    environment_pipeline_number:
    test_scenario_pipeline_number:
    closing_pipeline_number: 21
    # ansible_token:
    # google_chat_url:
