---
# WorkFlow: L1_wf03_test_scenario
# Survey: test_id, test_result_seq, seq, name
# Inventry: result_manager_url, pipeline_repo_domain, pipeline_repo_name
- name: Start Scenario
  ansible.builtin.import_playbook: L2_st01_start_scenario.yaml

- name: Run Online App
  ansible.builtin.import_playbook: L2_st02_run_online_app.yaml

- name: Data Entry
  ansible.builtin.import_playbook: L2_st03_data_entry.yaml

- name: Run Batch
  ansible.builtin.import_playbook: L2_st04_run_batch_app.yaml

- name: Assert Result
  ansible.builtin.import_playbook: L2_st05_assert_result.yaml

- name: Stop Online App
  ansible.builtin.import_playbook: L2_st06_stop_online_app.yaml

- name: Delete Jobs
  ansible.builtin.import_playbook: L2_st07_delete_job_all.yaml

- name: End Scenario
  ansible.builtin.import_playbook: L2_st10_end_scenario.yaml
