---
# JobTemplate: L2_ev06_insert_table
# Insert Table
# Survey: namespace_name, insert_table_image, insert_table_request
# Inventry: database_app_name, image_pull_secret_name, pg_user, pg_password, pg_port
- name: Insert Table
  hosts: localhost
  tasks:
    - name: Start timestamp
      set_fact: 
        start_timestamp: '{{ lookup(''pipe'', ''date "+%Y-%m-%d %H:%M:%S"'') }}'

    - name: Insert Table
      when: insert_table_request
      block:
        - name: Insert Table
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: batch/v1
              kind: Job
              metadata:
                name: insert-table-job
                namespace: "{{ namespace_name }}"
                labels:
                  app: insert-table-app
                  app.openshift.io/runtime: other-linux
              spec:
                template:
                  spec:
                    restartPolicy: Never
                    containers:
                      - name: insert-table-app
                        image: quay.io/rhn_consulting_kemori/{{ insert_table_image }}:latest
                        imagePullPolicy: Always
                        env:
                          - name: DB_USER
                            value: "{{ pg_user }}"
                          - name: DB_PASSWORD
                            value: "{{ pg_password }}"
                          - name: DB_SERVERNAME
                            value: "{{ database_app_name }}.{{ namespace_name }}.svc.cluster.local"
                          - name: DB_PORTNUMBER
                            value: "{{ pg_port }}"
                    imagePullSecrets:
                      - name: "{{ image_pull_secret_name }}"

        - name: Set test_result OK
          set_fact:
            test_result: "OK"

      rescue:
        - name: Set test_result NG
          set_fact:
            test_result: "NG"
        
    - name: End timestamp
      set_fact:
        end_timestamp: '{{ lookup(''pipe'', ''date "+%Y-%m-%d %H:%M:%S"'') }}'

    - name: Add test_task OK
      when: insert_table_request
      ansible.builtin.import_tasks:
        file: L3_tasks/L3_rp02_add_test_task.yaml
      vars:
        test_group: "環境立上"
        test_pipeline: "環境構築"
        test_task: "データロード"
        simulation_date: ""
        start_time: "{{ start_timestamp }}"
        end_time: "{{ end_timestamp }}"
        test_result: "{{ test_result }}"
        evidence_link: "https://console-openshift-console.{{ openshift_domain }}/k8s/ns/{{ namespace_name }}/jobs/insert-table-job"
        sw_category: ""
        sw_id: ""
        sw_name: ""
        sw_version: ""
