---
# JobTemplate: L2_ev04_create_database
# Create Database
# Survey: namespace_name, database_request
# Inventry: database_app_name, pg_user, pg_database, pg_password
- name: Create Database
  hosts: localhost
  tasks:
    - name: Start timestamp
      set_fact: 
        start_timestamp: '{{ lookup(''pipe'', ''date "+%Y-%m-%d %H:%M:%S"'') }}'

    - name: Create Database
      when: database_request
      block:
        - name: Create Database Deployment
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                namespace: "{{ namespace_name }}"
                name: "{{ database_app_name }}"
                labels:
                  app: postgresql
                  app.openshift.io/runtime: postgresql
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app: postgresql
                template:
                  metadata:
                    labels:
                      app: postgresql
                  spec:
                    containers:
                      - name: postgresql
                        image: registry.redhat.io/rhel8/postgresql-15:latest
                        imagePullPolicy: "IfNotPresent"
                        ports:
                          - containerPort: 5432
                        env:
                          - name: POSTGRESQL_USER
                            value: "{{ pg_user }}"
                          - name: POSTGRESQL_DATABASE
                            value: "{{ pg_database }}"
                          - name: POSTGRESQL_PASSWORD
                            value: "{{ pg_password }}"

        - name: Create Database Service
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: v1
              kind: Service
              metadata:
                name: "{{ database_app_name }}"
                namespace: "{{ namespace_name }}"
                labels:
                  app: postgresql
              spec:
                type: ClusterIP
                ports:
                  - name: 5432-tcp
                    protocol: TCP
                    port: 5432
                    targetPort: 5432
                sessionAffinity: None
                selector:
                  app: postgresql
              status:
                loadBalancer: {}

        - name: Set test_result OK
          set_fact:
            test_result: "OK"

      rescue:
        - name: Set test_result NG
          set_fact:
            test_result: "NG"
        
    - name: End timestamp
      set_fact:
        end_timestamp: '{{ lookup(''pipe'', ''date "+%Y-%m-%d %H:%M:%S"'') }}'

    - name: Add test_task OK
      when: database_request
      ansible.builtin.import_tasks:
        file: L3_tasks/L3_rp02_add_test_task.yaml
      vars:
        test_group: "環境立上"
        test_pipeline: "環境構築"
        test_task: "Database作成"
        simulation_date: ""
        start_time: "{{ start_timestamp }}"
        end_time: "{{ end_timestamp }}"
        test_result: "{{ test_result }}"
        evidence_link: "https://console-openshift-console.{{ openshift_domain }}/k8s/ns/{{ namespace_name }}/deployments/{{ database_app_name }}/"
        sw_category: ""
        sw_id: ""
        sw_name: ""
        sw_version: ""
