---
# JobTemplate: L2_ev03_create_secret
# Create a Secret
# Survey: namespace_name
# Extra vars: image_pull_secret_credential
# Inventry: image_pull_secret_name
- name: Create Secret
  hosts: localhost
  tasks:
    - name: Start timestamp
      set_fact: 
        start_timestamp: '{{ lookup(''pipe'', ''date "+%Y-%m-%d %H:%M:%S"'') }}'

    - name: Create Secret Block
      block:
        - name: Create a Image Pull Secret
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: v1
              kind: Secret
              metadata:
                namespace: "{{ namespace_name }}"
                name: "{{ image_pull_secret_name }}"
              data:
                .dockerconfigjson: "{{ image_pull_secret_credential }}"
              type: kubernetes.io/dockerconfigjson

        - name: Set test_result OK
          set_fact:
            test_result: "OK"

      rescue:
        - name: Set test_result NG
          set_fact:
            test_result: "NG"
        
    - name: End timestamp
      set_fact:
        end_timestamp: '{{ lookup(''pipe'', ''date "+%Y-%m-%d %H:%M:%S"'') }}'

    - name: Add test_task OK
      ansible.builtin.import_tasks:
        file: L3_tasks/L3_rp02_add_test_task.yaml
      vars:
        test_group: "環境立上"
        test_pipeline: "環境構築"
        test_task: "Secret作成"
        simulation_date: ""
        start_time: "{{ start_timestamp }}"
        end_time: "{{ end_timestamp }}"
        test_result: "{{ test_result }}"
        evidence_link: "https://console-openshift-console.{{ openshift_domain }}/k8s/ns/{{ namespace_name }}/secrets/{{ image_pull_secret_name }}"
        sw_category: ""
        sw_id: ""
        sw_name: ""
        sw_version: ""
