---
# JobTemplate: L2_ev03_create_secret
# Create a Secret
# Survey: namespace_name
# Extra vars: image_pull_secret_credential
# Inventry: image_pull_secret_name
- name: Create Secret
  hosts: localhost
  tasks:
    - name: Start timestamp
      ansible.builtin.debug:
        var: start_timestamp
      vars:
        start_timestamp: '{{ lookup(''pipe'', ''date "+%Y-%m-%d %H:%M:%S"'') }}'
      register: l2_ev03_start_timestamp

    - name: Create Secret Block
      block:
        - name: Create a Image Pull Secret
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: v1
              kind: Secret
              metadata:
                namespace: "{{ namespace_name }}"
                name: "{{ image_pull_secret_name }}"
              data:
                .dockerconfigjson: "{{ image_pull_secret_credential }}"
              type: kubernetes.io/dockerconfigjson

        - name: Set test_result
          ansible.builtin.debug:
            var: test_result
          vars:
            test_result: "OK"
          register: l2_ev03_result

      rescue:
        - name: Set test_result
          ansible.builtin.debug:
            var: test_result
          vars:
            test_result: "NG"
          register: l2_ev03_result
        
    - name: End timestamp
      ansible.builtin.debug:
        var: end_timestamp
      vars:
        end_timestamp: '{{ lookup(''pipe'', ''date "+%Y-%m-%d %H:%M:%S"'') }}'
      register: l2_ev03_end_timestamp

    - name: Add test_task OK
      ansible.builtin.import_tasks:
        file: L3_rp02_add_test_task.yaml
      vars:
        test_group: "環境立上"
        test_pipeline: "環境構築"
        test_task: "Secret作成"
        simulation_date: ""
        start_time: "{{ l2_ev03_start_timestamp.start_timestamp }}"
        end_time: "{{ l2_ev03_end_timestamp.end_timestamp }}"
        test_result: "{{ l2_ev03_result.test_result }}"
        evidence_link: "-"
        sw_category: ""
        sw_id: ""
        sw_name: ""
        sw_version: ""
