---
# JobTemplate L2_rp12_delete_job
# Delete Job
# Survey: namespace_name, job_name
- hosts: localhost
  tasks:
    - name: Delete Jobs
      kubernetes.core.k8s:
        state: absent
        api_version: batch/v1
        kind: Job
        namespace: "{{ namespace_name }}"
        name: "{{ job_name }}"
