---
# JobTemplate: L2_rp05_insert_table
# Insert Table
# Survey: namespace_name, insert_table_image
# Inventry: database_app_name, image_pull_secret_name, pg_user, pg_password, pg_port
- hosts: localhost
  tasks:
    - name: Insert Table
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: insert-table-job
            namespace: "{{ namespace_name }}"
            labels:
              app: insert-table-app
          spec:
            template:
              spec:
                restartPolicy: Never
                containers:
                  - name: insert-table-app
                    image: quay.io/rhn_consulting_kemori/{{ insert_table_image }}:latest
                    imagePullPolicy: Always
                    env:
                      - name: DB_USER
                        value: "{{ pg_user }}"
                      - name: DB_PASSWORD
                        value: "{{ pg_password }}"
                      - name: DB_SERVERNAME
                        value: "{{ database_app_name }}.{{ namespace_name }}.svc.cluster.local"
                      - name: DB_PORTNUMBER
                        value: "{{ pg_port }}"
                imagePullSecrets:
                  - name: "{{ image_pull_secret_name }}"
    
    # Search Pods
    - name: Search Pods
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ namespace_name }}"
        label_selectors:
          - app: insert-table-app
      register: l3_st01_result_pod

    # Get Podname
    - name: Get Podname
      set_fact: 
        podname: "{{ l3_st01_result_pod.resources[0].metadata.name }}"

    # Wait Pod Creation
    - name: Get Pod Info
      kubernetes.core.k8s_info:
        kind: Pod
        name: "{{ podname }}"
        namespace: "{{ namespace_name }}"
      register: l3_st01_result_pod
      until: l3_st01_result_pod.resources[0].status.phase == "Succeeded"
      retries: 5
      delay: 10              
