---
# JobTemplate: L2_rp07_deploy_result-manager
# Survey: namespace_name
- hosts: localhost
  tasks:
    - name: Deploy result-manager
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            namespace: "{{ namespace_name }}"
            name: result-manager
            labels:
              app: result-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: result-manager
            template:
              metadata:
                labels:
                  app: result-manager
              spec:
                containers:
                  - name: result-manager
                    image: quay.io/rhn_consulting_kemori/result-manager
                    imagePullPolicy: "IfNotPresent"
                    ports:
                      - containerPort: 8089
                        protocol: TCP
                    env:
                      - name: DB_HOST
                        value: postgresql.{{ namespace_name }}.svc.cluster.local
                      - name: DB_NAME
                        value: "{{ pg_database }}"
                      - name: DB_PASS
                        value: "{{ pg_password }}"
                      - name: DB_PORT
                        value: '{{ pg_port }}'
                      - name: DB_USER
                        value: "{{ pg_user }}"  
                imagePullSecrets:
                  - name: quayio

    - name: Service result-manager
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: result-manager
            namespace: "{{ namespace_name }}"
            labels:
              app: result-manager
          spec:
            type: ClusterIP
            ports:
              - name: 8089-tcp
                protocol: TCP
                port: 8089
                targetPort: 8089
            sessionAffinity: None
            selector:
              app: result-manager
          status:
            loadBalancer: {}

    - name: Route result-manager
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: result-manager
            namespace: "{{ namespace_name }}"
            labels:
              app: result-manager
          spec:
            host: result-manager-{{ namespace_name }}.{{ openshift_domain }}
            to:
              kind: Service
              name: result-manager
              weight: 100
            port:
              targetPort: 8089-tcp
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None
