---
# JobTemplate: L2_st07_end_scenario
# Survey: test_result_seq, test_id, seq(Integer), simulation_date
# Inventry:
# - result_manager_url, pipeline_repo_domain, pipeline_repo_name
# - google_chat_url, aap_controller_url, ansible_token
# - environment_pipeline_number, test_scenario_pipeline_number, closing_pipeline_number
- name: End Scenario 
  hosts: localhost
  tasks:
    - name: Git clone
      ansible.builtin.import_tasks:
        file: L3_tasks/L3_ut01_gitclone.yaml

    - name: Complete Notification
      ansible.builtin.import_tasks:
        file: L3_tasks/L3_rp05_run_complete_notification.yaml
      vars:
        text: "[test_result_seq={{ test_result_seq }}, test_id={{ test_id }}, simulation_date={{ simulation_date }}]\nシナリオが完了しました。\nhttps://{{ report_viewer_url }}/report?test_result_seq={{ test_result_seq }}"

    - name: Next Pipeline Kick
      ansible.builtin.import_tasks:
        file: L3_tasks/L3_ut02_kick_nextpipeline.yaml
      vars:
        seq: "{{ seq }}"
        test_id: "{{ test_id }}"
        test_result_seq: "{{ test_result_seq }}"
