---
# JobTemplate: L2_st06_stop_online_app
# Survey: test_id, test_result_seq, name, simulation_date
# Inventry: pipeline_repo_domain, pipeline_repo_name
- name: Start Scenario
  hosts: localhost
  tasks:
    # Git clone
    - name: Git clone
      ansible.builtin.import_tasks:
        file: L3_tasks/L3_ut01_gitclone.yaml

    # Include Vars
    - name: include_vars
      include_vars: 
        file: /tmp/{{ pipeline_repo_name }}/{{ test_id }}/test_scenario/{{ name }}/p5_stop_online_app/stop_online.yaml
        name: stop_online_vars

    # Stop Online
    # * namespace_name, delete_online_app_name
    # * test_result_seq, test_id, test_group, test_pipeline, simulation_date
    - name: Stop online App
      ansible.builtin.include_tasks:
        file: L3_tasks/L3_st04_delete_online_app.yaml
      vars:
        namespace_name: "{{ pipeline_vars.namespace_name }}"
        delete_online_app_name: "{{ item.name }}"
        test_result_seq: "{{ test_result_seq }}"
        test_id: "{{ test_id }}"
        test_group: "テストシナリオ"
        test_pipeline: "オンライン停止"
        simulation_date: "{{ simulation_date }}"
      loop: "{{ stop_online_vars.delete_online_apps }}"
      when: stop_online_vars.delete_online_apps != None

    # Report Summary
    - name: Report Pipeline Summary
      ansible.builtin.import_tasks:
        file: L3_tasks/L3_rp03_run_pipeline_summary.yaml
      vars:
        test_group: "テストシナリオ"
        test_pipeline: "オンライン停止"
        simulation_date : "{{ simulation_date }}"
