# Create Job_Template
# Extra_vars: 
# ----------------------------------------------
# aap_controller_url: ex) https://ansible-1.ckp7b.sandbox3023.opentlc.com
# ansible_user: ex) admin
# ansible_pw: Password
# inventory_name: demo-itst-inventory
# label_name: demo
# ----------------------------------------------
- name: Create a Workflow 
  hosts: localhost

  environment:
    CONTROLLER_HOST: "{{ aap_controller_url }}"
    CONTROLLER_USERNAME: "{{ ansible_user }}"
    CONTROLLER_PASSWORD: "{{ ansible_pw }}"
    CONTROLLER_VERIFY_SSL: false

  tasks:
    # L1_wf00_create_demo_report
    - name: L1_wf00_create_demo_report
      ansible.controller.workflow_job_template:
        name: test_L1_wf00_create_demo_report
        organization: Default
        inventory: "{{ inventory_name }}"
        state: present
        labels:
          - "{{ label_name }}"
        extra_vars:
          namespace_name: test-demo-report
          create_table_image: create_table
          insert_table_image: insert_table

    - name: L2_rp01_create_namespace
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp01_create_namespace
        workflow_job_template: test_L1_wf00_create_demo_report
        unified_job_template: L2_rp01_create_namespace
        organization: Default

    - name: L2_rp02_create_secret
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp02_create_secret
        workflow_job_template: test_L1_wf00_create_demo_report
        unified_job_template: L2_rp02_create_secret
        organization: Default

    - name: L2_rp03_create_database
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp03_create_database
        workflow_job_template: test_L1_wf00_create_demo_report
        unified_job_template: L2_rp03_create_database
        organization: Default

    - name: L2_rp04_create_table
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp04_create_table
        workflow_job_template: test_L1_wf00_create_demo_report
        unified_job_template: L2_rp04_create_table
        organization: Default

    - name: L2_rp05_insert_table
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp05_insert_table
        workflow_job_template: test_L1_wf00_create_demo_report
        unified_job_template: L2_rp05_insert_table
        organization: Default

    - name: L2_rp06_deploy_report-viewer
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp06_deploy_report-viewer
        workflow_job_template: test_L1_wf00_create_demo_report
        unified_job_template: L2_rp06_deploy_report-viewer
        organization: Default

    - name: L2_rp07_deploy_result-manager
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp07_deploy_result-manager
        workflow_job_template: test_L1_wf00_create_demo_report
        unified_job_template: L2_rp07_deploy_result-manager
        organization: Default

    - name: Link L2_rp01_create_namespace
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp01_create_namespace
        workflow_job_template: test_L1_wf00_create_demo_report
        organization: Default
        always_nodes:
          - L2_rp02_create_secret

    - name: Link L2_rp02_create_secret
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp02_create_secret
        workflow_job_template: test_L1_wf00_create_demo_report
        organization: Default
        always_nodes:
          - L2_rp03_create_database

    - name: Link L2_rp03_create_database
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp03_create_database
        workflow_job_template: test_L1_wf00_create_demo_report
        organization: Default
        always_nodes:
          - L2_rp04_create_table

    - name: Link L2_rp04_create_table
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp04_create_table
        workflow_job_template: test_L1_wf00_create_demo_report
        organization: Default
        always_nodes:
          - L2_rp05_insert_table

    - name: Link L2_rp05_insert_table
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp05_insert_table
        workflow_job_template: test_L1_wf00_create_demo_report
        organization: Default
        always_nodes:
          - L2_rp06_deploy_report-viewer

    - name: Link L2_rp06_deploy_report-viewer
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp06_deploy_report-viewer
        workflow_job_template: test_L1_wf00_create_demo_report
        organization: Default
        always_nodes:
          - L2_rp07_deploy_result-manager

    # L1_wf01_init
    - name: L1_wf01_init
      ansible.controller.workflow_job_template:
        name: test_L1_wf01_init
        organization: Default
        inventory: "{{ inventory_name }}"
        state: present
        labels:
          - "{{ label_name }}"
        survey_enabled: true
        survey_spec:
          name: Simple
          description: Description of the simple survey
          spec:
            - type: text
              question_name: test_id
              variable: test_id
              required: true
    
    - name: L2_ut01_init_job
      ansible.controller.workflow_job_template_node:
        identifier: L2_ut01_init_job
        workflow_job_template: test_L1_wf01_init
        unified_job_template: L2_ut01_init_job
        organization: Default
