---
# Create Inventory
# Extra_vars: 
#  - inventory_name: demo-itst-inventory
#  - label_name: demo
#  - aap_controller_url: ex) https://ansible-1.ckp7b.sandbox3023.opentlc.com
#  - ansible_user: ex) admin
#  - ansible_pw: Password
#  - ansible_token: Created Token
#  - aap_api_url: AAP2.5 -> api/controller/v2, Before -> api/v2
#  - openshift_domain: ex) apps.rosa.rosa-nsdsm.9et7.p3.openshiftapps.com
#  - google_chat_url: Google Chat URL
# Notice:
#  - environment_pipeline_number: Change to WorkFlow Number for L1_wf02_environment
#  - test_scenario_pipeline_number: Change to WorkFlow Number for L1_wf03_test_scenario
#  - closing_pipeline_number: Change to WorkFlow Number for L1_wf04_closing
- name: Create a Inventory 
  hosts: localhost

  environment:
    CONTROLLER_HOST: "{{ aap_controller_url }}"
    CONTROLLER_USERNAME: "{{ ansible_user }}"
    CONTROLLER_PASSWORD: "{{ ansible_pw }}"
    CONTROLLER_VERIFY_SSL: false

  tasks:
    - name: create a inventory
      awx.awx.inventory:
        name: "{{ inventory_name }}"
        description: "Variables Setting"
        organization: "Default"
        state: present
        kind: ""
        labels:
          - "{{ label_name }}"
        variables:
          openshift_domain: "{{ openshift_domain }}"
          result_manager_url: result-manager-demo-report.{{ openshift_domain }}
          report_viewer_url: report-viewer-demo-report.{{ openshift_domain }}
          image_pull_secret_name: quayio
          database_app_name: postgresql
          pg_user: test
          pg_database: test
          pg_password: test
          pg_port: '5432'
          pipeline_repo_domain: rhn-consulting-kemori
          pipeline_repo_name: demo-itst-test
          aap_controller_url: "{{ aap_controller_url }}"
          aap_api_url: "{{ aap_api_url }}"
          ansible_token: "{{ ansible_token }}"
          google_chat_url: "{{ google_chat_url }}"
          pvc_name: demo-efs-pvc1
          pvc_access_mode: ReadWriteMany
          strage_class_name: efs-csi
          pvc_strage_size: 1Gi
          environment_pipeline_number: 62
          test_scenario_pipeline_number: 63
          closing_pipeline_number: 64
