# Create Job_Template
# Extra_vars: 
# ----------------------------------------------
# aap_controller_url: ex) https://ansible-1.ckp7b.sandbox3023.opentlc.com
# ansible_user: ex) admin
# ansible_pw: Password
# inventory_name: demo-itst-inventory
# label_name: demo
# ----------------------------------------------
- name: Create a Workflow 
  hosts: localhost

  environment:
    CONTROLLER_HOST: "{{ aap_controller_url }}"
    CONTROLLER_USERNAME: "{{ ansible_user }}"
    CONTROLLER_PASSWORD: "{{ ansible_pw }}"
    CONTROLLER_VERIFY_SSL: false

  tasks:
    # L1_wf00_create_demo_report
    - name: L1_wf00_create_demo_report
      ansible.controller.workflow_job_template:
        name: L1_wf00_create_demo_report
        organization: Default
        inventory: "{{ inventory_name }}"
        state: present
        labels:
          - "{{ label_name }}"
        extra_vars:
          namespace_name: demo-report
          create_table_image: create_table
          insert_table_image: insert_table

    - name: L2_rp01_create_namespace
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp01_create_namespace
        workflow_job_template: L1_wf00_create_demo_report
        unified_job_template: L2_rp01_create_namespace
        organization: Default

    - name: L2_rp02_create_secret
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp02_create_secret
        workflow_job_template: L1_wf00_create_demo_report
        unified_job_template: L2_rp02_create_secret
        organization: Default

    - name: L2_rp03_create_database
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp03_create_database
        workflow_job_template: L1_wf00_create_demo_report
        unified_job_template: L2_rp03_create_database
        organization: Default

    - name: L2_rp04_create_table
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp04_create_table
        workflow_job_template: L1_wf00_create_demo_report
        unified_job_template: L2_rp04_create_table
        organization: Default

    - name: L2_rp05_insert_table
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp05_insert_table
        workflow_job_template: L1_wf00_create_demo_report
        unified_job_template: L2_rp05_insert_table
        organization: Default

    - name: L2_rp06_deploy_report-viewer
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp06_deploy_report-viewer
        workflow_job_template: L1_wf00_create_demo_report
        unified_job_template: L2_rp06_deploy_report-viewer
        organization: Default

    - name: L2_rp07_deploy_result-manager
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp07_deploy_result-manager
        workflow_job_template: L1_wf00_create_demo_report
        unified_job_template: L2_rp07_deploy_result-manager
        organization: Default

    - name: L2_rp08_deploy_start-scenario
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp08_deploy_start-scenario
        workflow_job_template: L1_wf00_create_demo_report
        unified_job_template: L2_rp08_deploy_start-scenario
        organization: Default

    - name: Link L2_rp01_create_namespace
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp01_create_namespace
        workflow_job_template: L1_wf00_create_demo_report
        organization: Default
        always_nodes:
          - L2_rp02_create_secret

    - name: Link L2_rp02_create_secret
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp02_create_secret
        workflow_job_template: L1_wf00_create_demo_report
        organization: Default
        always_nodes:
          - L2_rp03_create_database

    - name: Link L2_rp03_create_database
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp03_create_database
        workflow_job_template: L1_wf00_create_demo_report
        organization: Default
        always_nodes:
          - L2_rp04_create_table

    - name: Link L2_rp04_create_table
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp04_create_table
        workflow_job_template: L1_wf00_create_demo_report
        organization: Default
        always_nodes:
          - L2_rp05_insert_table

    - name: Link L2_rp05_insert_table
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp05_insert_table
        workflow_job_template: L1_wf00_create_demo_report
        organization: Default
        always_nodes:
          - L2_rp06_deploy_report-viewer

    - name: Link L2_rp06_deploy_report-viewer
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp06_deploy_report-viewer
        workflow_job_template: L1_wf00_create_demo_report
        organization: Default
        always_nodes:
          - L2_rp07_deploy_result-manager

    - name: Link L2_rp07_deploy_result-manager
      ansible.controller.workflow_job_template_node:
        identifier: L2_rp07_deploy_result-manager
        workflow_job_template: L1_wf00_create_demo_report
        organization: Default
        always_nodes:
          - L2_rp08_deploy_start-scenario

    # L1_wf01_init
    - name: L1_wf01_init
      ansible.controller.workflow_job_template:
        name: L1_wf01_init
        organization: Default
        inventory: "{{ inventory_name }}"
        state: present
        labels:
          - "{{ label_name }}"
        survey_enabled: true
        survey_spec:
          name: Simple
          description: Description of the simple survey
          spec:
            - type: text
              question_name: test_id
              variable: test_id
              required: true
    
    - name: L2_ut01_init_job
      ansible.controller.workflow_job_template_node:
        identifier: L2_ut01_init_job
        workflow_job_template: L1_wf01_init
        unified_job_template: L2_ut01_init_job
        organization: Default

    # L1_wf02_environment
    - name: L1_wf02_environment
      ansible.controller.workflow_job_template:
        name: L1_wf02_environment
        organization: Default
        inventory: "{{ inventory_name }}"
        state: present
        labels:
          - "{{ label_name }}"
        survey_enabled: true
        survey_spec:
          name: Simple
          description: Description of the simple survey
          spec:
            - type: text
              question_name: test_id
              variable: test_id
              required: true
            - type: text
              question_name: test_result_seq
              variable: test_result_seq
              required: true
            - type: integer
              question_name: seq
              variable: seq
              required: true
            - type: text
              question_name: name
              variable: name
              required: true
    
    - name: L2_ev01_gitclone_setparam
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev01_gitclone_setparam
        workflow_job_template: L1_wf02_environment
        unified_job_template: L2_ev01_gitclone_setparam
        organization: Default
    
    - name: L2_ev02_create_namespace
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev02_create_namespace
        workflow_job_template: L1_wf02_environment
        unified_job_template: L2_ev02_create_namespace
        organization: Default

    - name: L2_ev03_create_secret
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev03_create_secret
        workflow_job_template: L1_wf02_environment
        unified_job_template: L2_ev03_create_secret
        organization: Default

    - name: L2_ev04_create_database
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev04_create_database
        workflow_job_template: L1_wf02_environment
        unified_job_template: L2_ev04_create_database
        organization: Default

    - name: L2_ev05_create_table
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev05_create_table
        workflow_job_template: L1_wf02_environment
        unified_job_template: L2_ev05_create_table
        organization: Default

    - name: L2_ev06_insert_table
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev06_insert_table
        workflow_job_template: L1_wf02_environment
        unified_job_template: L2_ev06_insert_table
        organization: Default

    - name: L2_ev07_create_pvc
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev07_create_pvc
        workflow_job_template: L1_wf02_environment
        unified_job_template: L2_ev07_create_pvc
        organization: Default

    - name: L2_ev08_run_data_setup_app
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev08_run_data_setup_app
        workflow_job_template: L1_wf02_environment
        unified_job_template: L2_ev08_run_data_setup_app
        organization: Default

    - name: L2_ev10_create_kafka
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev10_create_kafka
        workflow_job_template: L1_wf02_environment
        unified_job_template: L2_ev10_create_kafka
        organization: Default

    - name: L2_ev09_end_provisioning
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev09_end_provisioning
        workflow_job_template: L1_wf02_environment
        unified_job_template: L2_ev09_end_provisioning
        organization: Default

    - name: Link L2_ev01_gitclone_setparam
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev01_gitclone_setparam
        workflow_job_template: L1_wf02_environment
        organization: Default
        always_nodes:
          - L2_ev02_create_namespace

    - name: Link L2_ev02_create_namespace
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev02_create_namespace
        workflow_job_template: L1_wf02_environment
        organization: Default
        always_nodes:
          - L2_ev03_create_secret

    - name: Link L2_ev03_create_secret
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev03_create_secret
        workflow_job_template: L1_wf02_environment
        organization: Default
        always_nodes:
          - L2_ev04_create_database

    - name: Link L2_ev04_create_database
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev04_create_database
        workflow_job_template: L1_wf02_environment
        organization: Default
        always_nodes:
          - L2_ev05_create_table

    - name: Link L2_ev05_create_table
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev05_create_table
        workflow_job_template: L1_wf02_environment
        organization: Default
        always_nodes:
          - L2_ev06_insert_table

    - name: Link L2_ev06_insert_table
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev06_insert_table
        workflow_job_template: L1_wf02_environment
        organization: Default
        always_nodes:
          - L2_ev07_create_pvc

    - name: Link L2_ev07_create_pvc
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev07_create_pvc
        workflow_job_template: L1_wf02_environment
        organization: Default
        always_nodes:
          - L2_ev08_run_data_setup_app

    - name: Link L2_ev08_run_data_setup_app
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev08_run_data_setup_app
        workflow_job_template: L1_wf02_environment
        organization: Default
        always_nodes:
          - L2_ev10_create_kafka

    - name: Link L2_ev10_create_kafka
      ansible.controller.workflow_job_template_node:
        identifier: L2_ev10_create_kafka
        workflow_job_template: L1_wf02_environment
        organization: Default
        always_nodes:
          - L2_ev09_end_provisioning

    # L1_wf03_test_scenario
    - name: L1_wf03_test_scenario
      ansible.controller.workflow_job_template:
        name: L1_wf03_test_scenario
        organization: Default
        inventory: "{{ inventory_name }}"
        state: present
        labels:
          - "{{ label_name }}"
        survey_enabled: true
        survey_spec:
          name: Simple
          description: Description of the simple survey
          spec:
            - type: text
              question_name: test_id
              variable: test_id
              required: true
            - type: text
              question_name: test_result_seq
              variable: test_result_seq
              required: true
            - type: integer
              question_name: seq
              variable: seq
              required: true
            - type: text
              question_name: name
              variable: name
              required: true
    
    - name: L2_st01_start_scenario
      ansible.controller.workflow_job_template_node:
        identifier: L2_st01_start_scenario
        workflow_job_template: L1_wf03_test_scenario
        unified_job_template: L2_st01_start_scenario
        organization: Default
    
    - name: L2_st02_run_online_app
      ansible.controller.workflow_job_template_node:
        identifier: L2_st02_run_online_app
        workflow_job_template: L1_wf03_test_scenario
        unified_job_template: L2_st02_run_online_app
        organization: Default

    - name: L2_st03_data_entry
      ansible.controller.workflow_job_template_node:
        identifier: L2_st03_data_entry
        workflow_job_template: L1_wf03_test_scenario
        unified_job_template: L2_st03_data_entry
        organization: Default

    - name: L2_st04_run_batch_app
      ansible.controller.workflow_job_template_node:
        identifier: L2_st04_run_batch_app
        workflow_job_template: L1_wf03_test_scenario
        unified_job_template: L2_st04_run_batch_app
        organization: Default

    - name: L2_st05_assert_result
      ansible.controller.workflow_job_template_node:
        identifier: L2_st05_assert_result
        workflow_job_template: L1_wf03_test_scenario
        unified_job_template: L2_st05_assert_result
        organization: Default

    - name: L2_st06_stop_online_app
      ansible.controller.workflow_job_template_node:
        identifier: L2_st06_stop_online_app
        workflow_job_template: L1_wf03_test_scenario
        unified_job_template: L2_st06_stop_online_app
        organization: Default

    - name: L2_st07_delete_job_all
      ansible.controller.workflow_job_template_node:
        identifier: L2_st07_delete_job_all
        workflow_job_template: L1_wf03_test_scenario
        unified_job_template: L2_st07_delete_job_all
        organization: Default

    - name: L2_st10_end_scenario
      ansible.controller.workflow_job_template_node:
        identifier: L2_st10_end_scenario
        workflow_job_template: L1_wf03_test_scenario
        unified_job_template: L2_st10_end_scenario
        organization: Default
    
    - name: Link L2_st01_start_scenario
      ansible.controller.workflow_job_template_node:
        identifier: L2_st01_start_scenario
        workflow_job_template: L1_wf03_test_scenario
        organization: Default
        always_nodes:
          - L2_st02_run_online_app
    
    - name: Link L2_st02_run_online_app
      ansible.controller.workflow_job_template_node:
        identifier: L2_st02_run_online_app
        workflow_job_template: L1_wf03_test_scenario
        organization: Default
        always_nodes:
          - L2_st03_data_entry

    - name: Link L2_st03_data_entry
      ansible.controller.workflow_job_template_node:
        identifier: L2_st03_data_entry
        workflow_job_template: L1_wf03_test_scenario
        organization: Default
        always_nodes:
          - L2_st04_run_batch_app

    - name: Link L2_st04_run_batch_app
      ansible.controller.workflow_job_template_node:
        identifier: L2_st04_run_batch_app
        workflow_job_template: L1_wf03_test_scenario
        organization: Default
        always_nodes:
          - L2_st05_assert_result

    - name: Link L2_st05_assert_result
      ansible.controller.workflow_job_template_node:
        identifier: L2_st05_assert_result
        workflow_job_template: L1_wf03_test_scenario
        organization: Default
        always_nodes:
          - L2_st06_stop_online_app

    - name: Link L2_st06_stop_online_app
      ansible.controller.workflow_job_template_node:
        identifier: L2_st06_stop_online_app
        workflow_job_template: L1_wf03_test_scenario
        organization: Default
        always_nodes:
          - L2_st07_delete_job_all

    - name: Link L2_st07_delete_job_all
      ansible.controller.workflow_job_template_node:
        identifier: L2_st07_delete_job_all
        workflow_job_template: L1_wf03_test_scenario
        organization: Default
        always_nodes:
          - L2_st10_end_scenario

    # L1_wf04_closing
    - name: L1_wf04_closing
      ansible.controller.workflow_job_template:
        name: L1_wf04_closing
        organization: Default
        inventory: "{{ inventory_name }}"
        state: present
        labels:
          - "{{ label_name }}"
        survey_enabled: true
        survey_spec:
          name: Simple
          description: Description of the simple survey
          spec:
            - type: text
              question_name: test_id
              variable: test_id
              required: true
            - type: text
              question_name: test_result_seq
              variable: test_result_seq
              required: true
    
    - name: L2_ut02_closing_job
      ansible.controller.workflow_job_template_node:
        identifier: L2_ut02_closing_job
        workflow_job_template: L1_wf04_closing
        unified_job_template: L2_ut02_closing_job
        organization: Default
