---
# Tasks: L3_st07_delete_namespace
# Extra vars: namespace_name
- name: Start timestamp
  set_fact: 
    start_timestamp: '{{ lookup(''pipe'', ''date "+%Y-%m-%d %H:%M:%S"'') }}'

- name: Delete a NameSpace
  kubernetes.core.k8s:
    name: "{{ namespace_name }}"
    api_version: v1
    kind: Namespace
    state: absent

- name: End timestamp
  set_fact:
    end_timestamp: '{{ lookup(''pipe'', ''date "+%Y-%m-%d %H:%M:%S"'') }}'

- name: Add test_task OK
  ansible.builtin.import_tasks:
    file: L3_tasks/L3_rp02_add_test_task.yaml
  vars:
    test_group: "クロージング"
    test_pipeline: "環境スクラップ"
    test_task: "NameSpace削除"
    simulation_date: ""
    start_time: "{{ start_timestamp }}"
    end_time: "{{ end_timestamp }}"
    test_result: "OK"
    evidence_link: "-"
    sw_category: ""
    sw_id: ""
    sw_name: ""
    sw_version: ""
