---
# Tasks: L3_ut02_kick_nextpipeline
# Extra vars: test_id, test_result_seq, seq(Integer)
# Invantry: aap_controller_url, ansible_token, environment_pipeline_number, test_scenario_pipeline_number, closing_pipeline_number
- name: Select Next Pipeline
  debug:
    var: next_pipeline
  vars:
    next_pipeline: '{{ pipeline_vars.pipelines | selectattr("seq", "defined") | selectattr("seq", "eq", seq + 1) }}'
  register: search_result

- name: Print Next Pipeline
  debug:
    msg: 'test_id={{ test_id }}, test_result_seq={{ test_result_seq }}, type={{ item.type }}, seq={{ item.seq }}, name={{ item.name }}'
  loop: '{{ search_result.next_pipeline }}'

# Environment kick
- name: REST CALL for environment
  ansible.builtin.uri:
    url: "{{ aap_controller_url }}/api/controller/v2/workflow_job_templates/{{ environment_pipeline_number }}/launch/"
    method: POST
    body_format: json
    status_code: 201
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ ansible_token }}
    body: |-
      {
        "extra_vars": {
          "test_id": "{{ test_id }}",
          "test_result_seq": "{{ test_result_seq }}",
          "seq": {{ item.seq }},
          "name": "{{ item.name }}"
        }
      }
  register: result
  with_items: '{{ search_result.next_pipeline }}'
  when: item.type == "environment"

# Test_Scenario kick
- name: REST CALL for test_scenario
  ansible.builtin.uri:
    url: "{{ aap_controller_url }}/api/controller/v2/workflow_job_templates/{{ test_scenario_pipeline_number }}/launch/"
    method: POST
    body_format: json
    status_code: 201
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ ansible_token }}
    body: |-
      {
        "extra_vars": {
          "test_id": "{{ test_id }}",
          "test_result_seq": "{{ test_result_seq }}",
          "seq": {{ item.seq }},
          "name": "{{ item.name }}"
        }
      }
  register: result
  with_items: '{{ search_result.next_pipeline }}'
  when: item.type == "test_scenario"

# Closing kick
- name: REST CALL for closing pipeline
  ansible.builtin.uri:
    url: "{{ aap_controller_url }}/api/controller/v2/workflow_job_templates/{{ closing_pipeline_number }}/launch/"
    method: POST
    body_format: json
    status_code: 201
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ ansible_token }}
    body: |-
      {
        "extra_vars": {
          "test_id": "{{ test_id }}",
          "test_result_seq": "{{ test_result_seq }}"
        }
      }
  register: result
  with_items: '{{ search_result.next_pipeline }}'
  when: item.type == "closing"

# Print Result
- name: Print Result
  debug:
    var: result
